package com.telegram.bot.states;

public enum OwnersStates {
    REGISTERED_SHELTERS_NAME,
    REGISTERED_SHELTERS_DESCRIPTION,
    REGISTRATION_SHELTERS_SECURITY_CONTACT,
    REGISTRATION_SHELTERS_SAFETY_RECOMMENDATION,
    REGISTRATION_SHELTERS_CONTACT,
    REGISTRATION_SHELTERS_SCHEDULE,
    REGISTRATION_SHELTERS_KIND,
    REGISTRATION_SHELTERS_WAIT,
    REGISTRATION_ANIMAL_COLOR,
    REGISTRATION_ANIMAL_DESCRIPTION,
    REGISTRATION_ANIMAL_KIND,
    REGISTRATION_ANIMAL_PHOTO,
    REJECT_VOLUNTEER,
    GET_CHAT_ID_PUT_MESSAGE,

}
